# Generated by Django 5.2.13 on 2026-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tenants_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseconfig',
            name='conn_max_age',
            field=models.IntegerField(default=60, help_text='Persistent connection timeout in seconds (0 = close after each request).'),
        ),
    ]
