# Generated by Django 5.2.13 on 2026-04-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tenants_router', '0002_alter_tenantdatabaseconfig_conn_max_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdatabaseconfig',
            name='atomic_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantdatabaseconfig',
            name='auto_commit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantdatabaseconfig',
            name='conn_health_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantdatabaseconfig',
            name='time_zone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
 