# Generated by Django 5.2.13 on 2026-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tenants_router', '0004_alter_tenantdatabaseconfig_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseconfig',
            name='atomic_request',
            field=models.BooleanField(default=False),
        ),
    ]
 