# Generated by Django 5.2.13 on 2026-04-24 17:05
 
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('django_tenants_router', '0005_alter_tenantdatabaseconfig_atomic_request'),
    ]
 
    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseconfig',
            name='auto_commit',
            field=models.BooleanField(default=True),
        ),
    ]